config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get '/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]
  resources :reservations, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  
  enum consultation_count: { 初診: 0, ２回以上: 1}
  enum treatment: { あり: 0, なし: 1}, _prefix: true
  enum side_effects: { あり: 0, なし: 1}, _prefix: true
  enum pregnancy: { なし: 0, 可能性あり: 1, 妊娠中: 2, 授乳中: 3}, _prefix: true
  enum purpose: { 診断＋診察＋処方: 0, 診察＋処方: 1, 処方のみ: 2}

  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :timeoutable

  enum sex: { 男性: 0, 女性: 1}
  
  attachment :profile_image
  
  has_many :reservations, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birth_date, :sex, :tel, :kana])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      flash[:notice] = "予約に成功しました"
      redirect_to reservation_path(@reservation)
    else 
      render :new
    end
  end

  def index
  end

  def show
    @reservation = Reservation.find(params[:id])
  end
  
  def edit
    @reservation = Reservation.find(params[:id])
    if @reservation.user == current_user
      render :edit
    else
      redirect_to reservations_path
    end
  end
  
  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:notice] = "予約更新に成功しました"
      redirect_to reservation_path(@reservation)
    else
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to new_reservation_path
  end
  
  private

  def reservation_params
    params.require(:reservation).permit(:reservation_date, :reservation_time, :consultation_count, :tel, :symptoms, :body_parts,
                                        :starting_point, :treatment, :prescription, :side_effects, :other_diseases, :hospital_name,
                                        :pregnancy, :purpose, :request)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all.order(created_at: :desc)
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :birth_date, :sex, :email, :tel, :kana)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>院長挨拶/施設紹介</h1>

app/views/homes/top.html.erb
<h1>専門/特徴/診療時間</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartDoctor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li><a href="/">ホーム</a></li>
      <li><a href="/about">当院について</a></li>
      <li><%= link_to 'マイページ', user_path(current_user.id) %></li>
      <li><%= link_to 'ユーザ一覧', users_path %></li>
      <li><%= link_to '新規予約', new_reservation_path %></li>

      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><a href="/">ホーム</a></li>
      <li><a href="/about">当院について</a></li>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
    <%= yield %>
  </body>
  
</html>

app/views/reservations/edit.html.erb
<h2 class="mt-3">予約更新フォーム</h2>
  <% if @reservation.errors.any? %>
    <%= @reservation.errors.count %>error prohibited this obj from being saved:
    <% @reservation.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form_with model: @reservation, local:true do |f| %>
      <h6>受診希望日を選択してください。</h6>
      <%= f.date_field :reservation_date %>
      
      <h6>受診希望時間を選択してください。</h6>
      <%= f.time_field :reservation_time %>
      
      <h6>当クリニックの受診回数を選択してください。</h6>
      <%= f.select :consultation_count, [["初診", 0], ["２回以上", 1]], include_blank: "選択して下さい" %>
      
      <h6>電話番号を教えてください。（半角、「-」あり）</h6>
      <%= f.text_field :tel %>
      
      <h6>どんな症状がありますか？</h6>
      <%= f.text_area :symptoms %>
      
      <h6>症状のある身体部位はどこですか？</h6>
      <%= f.text_field :body_parts %>
      
      <h6>症状が出たのはいつからですか？</h6>
      <%= f.date_field :starting_point %>
      
      <h6>今回の症状でこれまでに治療を受けていますか？</h6>
      <%= f.select :treatment, [["あり", 0], ["なし", 1]], include_blank: "選択して下さい" %>
      
      <h6>服用中の薬があれば教えてください。</h6>
      <%= f.text_area :prescription %>
      
      <h6>副作用の有無を選択してください。</h6>
      <%= f.select :side_effects, [["あり", 0], ["なし", 1]], include_blank: "選択して下さい" %>
      
      <h6>今回以外に罹患中の病気があれば教えてください。</h6>
      <%= f.text_field :other_diseases %>
      
      <h6>かかりつけの病院があれば教えてください。</h6>
      <%= f.text_area :hospital_name %>
      
      <h6>妊娠の有無を選択してください。</h6>
      <%= f.select :pregnancy, [["なし", 0], ["可能性あり", 1], ["妊娠中", 2], ["授乳中", 3]], include_blank: "選択して下さい" %>
      
      <h6>今回の受診の目的を教えてください。</h6>
      <%= f.select :purpose, [["診断＋診察＋処方", 0], ["診察＋処方", 1], ["処方のみ", 2]], include_blank: "選択して下さい" %>
      
      <h6>最後に医師への要望があれば教えてください。</h6>
      <%= f.text_area :request %>
      
      <%= f.submit '更新', :class=>"btn btn-success" %>
    <% end %>
  </div>

app/views/reservations/new.html.erb
  <h2 class="mt-3">予約フォーム</h2>
  <% if @reservation.errors.any? %>
    <%= @reservation.errors.count %>error prohibited this obj from being saved:
    <% @reservation.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= form_with model: @reservation, local:true do |f| %>
      <h6>受診希望日を選択してください。</h6>
      <%= f.date_field :reservation_date %>
      
      <h6>受診希望時間を選択してください。</h6>
      <%= f.time_field :reservation_time %>
      
      <h6>当クリニックの受診回数を選択してください。</h6>
      <%= f.select :consultation_count, [["初診", 0], ["２回以上", 1]], include_blank: "選択して下さい" %>
      
      <h6>電話番号を教えてください。（半角、「-」あり）</h6>
      <%= f.text_field :tel %>
      
      <h6>どんな症状がありますか？</h6>
      <%= f.text_area :symptoms %>
      
      <h6>症状のある身体部位はどこですか？</h6>
      <%= f.text_field :body_parts %>
      
      <h6>症状が出たのはいつからですか？</h6>
      <%= f.date_field :starting_point %>
      
      <h6>今回の症状でこれまでに治療を受けていますか？</h6>
      <%= f.select :treatment, [["あり", 0], ["なし", 1]], include_blank: "選択して下さい" %>
      
      <h6>服用中の薬があれば教えてください。</h6>
      <%= f.text_area :prescription %>
      
      <h6>副作用の有無を選択してください。</h6>
      <%= f.select :side_effects, [["あり", 0], ["なし", 1]], include_blank: "選択して下さい" %>
      
      <h6>今回以外に罹患中の病気があれば教えてください。</h6>
      <%= f.text_field :other_diseases %>
      
      <h6>かかりつけの病院があれば教えてください。</h6>
      <%= f.text_area :hospital_name %>
      
      <h6>妊娠の有無を選択してください。</h6>
      <%= f.select :pregnancy, [["なし", 0], ["可能性あり", 1], ["妊娠中", 2], ["授乳中", 3]], include_blank: "選択して下さい" %>
      
      <h6>今回の受診の目的を教えてください。</h6>
      <%= f.select :purpose, [["診断＋診察＋処方", 0], ["診察＋処方", 1], ["処方のみ", 2]], include_blank: "選択して下さい" %>
      
      <h6>最後に医師への要望があれば教えてください。</h6>
      <%= f.text_area :request %>
      
      <%= f.submit '予約', :class=>"btn btn-success" %>
    <% end %>
  </div>
  

app/views/reservations/show.html.erb
<div class="col-md-8 offset-md-1">
  <h2>予約詳細</h2>
  <div class="table">
    <%= attachment_image_tag @reservation.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %><br>
    <%= link_to @reservation.user.name, user_path(@reservation.user) %>
    <h6>受診日</h6><%= @reservation.reservation_date %>
  　<h6>受診時間</h6><%= @reservation.reservation_time %>
  　<h6>受診回数</h6><%= @reservation.consultation_count %>
  　<h6>電話番号</h6><%= @reservation.tel %>
  　<h6>症状</h6><%= @reservation.symptoms %>
  　<h6>身体部位</h6><%= @reservation.body_parts %>
  　<h6>起点日</h6><%= @reservation.starting_point %>
    <h6>治療の有無</h6><%= @reservation.treatment %>
  　<h6>処方の有無</h6><%= @reservation.prescription %>
  　<h6>副作用の有無</h6><%= @reservation.side_effects %>
  　<h6>他の罹患</h6><%= @reservation.other_diseases %>
  　<h6>病院名</h6><%= @reservation.hospital_name %>
  　<h6>妊娠の有無</h6><%= @reservation.pregnancy %>
  　<h6>受診の目的</h6><%= @reservation.purpose %>
  　<h6>医師への要望</h6><%= @reservation.request %>
      <% if @reservation.user == current_user %>
      <a class="btn btn-sm btn-success" href="/reservations/<%= @reservation.id %>/edit">予約更新</a>
      <% end %>
      <% if @reservation.user == current_user %>
      <a data-confirm="キャンセルしますか？" class="btn btn-sm btn-danger" rel="nofollow" data-method="delete" href="/reservations/<%= @reservation.id %>">予約キャンセル</a>
      <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>プロフィール編集</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <h6>プロフィール画像</h6>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <h6>お名前</h6>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <h6>フリガナ</h6>
          <%= f.text_field :kana %>
        </div>
        <div class="form-group">
          <h6>生年月日</h6>
          <%= f.date_select :birth_date, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1990, 1, 1) %>
        </div>
        <div class="form-group">
          <h6>性別</h6>
          <%= f.label :男性  %>
          <%= f.radio_button :sex, :男性 %>
          <%= f.label :女性  %>
          <%= f.radio_button :sex, :女性 %>
        </div>
        <div class="form-group">
          <h6>電話番号</h6>
          <%= f.text_field :tel %>
        </div>
        <div class="form-group">
          <h6>メールアドレス</h6>
          <%= f.email_field :email %>
        </div>
        <div class="form-group">
          <%= f.submit '更新', :class=>"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <h2>ユーザ一覧</h2>
      <table class="table">
      　<thead>
          <tr>
          　<th>image</th>
          　<th>name</th>
          　<th></th>
          　<th colspan="3"></th>
          </tr>
      　</thead>
      　<tbody>
          <% @users.each do |user| %>
            <tr>
            　<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></td>
            　<td><%= user.name %></td>
            　<td><%= link_to "ユーザ詳細", user_path(user) %></td>
            </tr>
          <% end %>
      　</tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>プロフィール</h2>
<div class="profile-container">
  <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %>
  <table class="table">
    <tbody><tr></tr>
      <tr>
        <th>ID</th>
        <th><%= @user.id %></th>
      </tr>
      <tr>
        <th>お名前</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <th><%= @user.email %></th>
      </tr>
    </tbody></table>
  </table>
  <div class="row">
    <a href="/users/<%= @user.id %>/edit">プロフィール編集</a>
  </div>
</div>